name: Update word list

on:
  schedule:
    # The time is arbitrary
    - cron: "40 20 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-words:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "22.x"

      - run: |
          if node updateWords.ts; then
            git config user.name "github-actions[bot]"
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add .
            git commit -m "Update data.json"
            git push
          fi
